### ISSUE TITLE
Error 504 Gateway timeout

### ISSUE THREAD

**Issue by mart834d** [bjowes/cypress-ntlm-auth#107]
Current behavior:

When I run my test, I need to auth with NTML. When I do so, it seems like I get authenticated, but I get an error. Error 504 Gateway timeout.
https://gyazo.com/41987db5ceba627491f4d165079d45e2

Desired behavior:

What I want to happen is, being authenticated, and not getting this error. And being sent into the webpage which I ask for.

Versions

Im using Cypress version 4.1.0

**Comment by bjowes** [comment]
Hi @mart834d , I think you see a hint in the error message - 'unable to get issuer certificate'. Please have a look at the [HTTPS/SSL/TLS issues](https://github.com/bjowes/cypress-ntlm-auth#httpsssltls-issues) section of the readme, I would guess that you are facing problems with a corporate proxy that is decrypting the SSL traffic. 

Let me know if you need more detailed support

**Comment by mart834d** [comment]
@bjowes Yes I've been reading it through. I've tried this in my package.json have this inside the script tag

"scripts": {"unsafe-cypress-ntlm": "set NODE_TLS_REJECT_UNAUTHORIZED=0 && npm run cypress-ntlm",
        "ntlm-proxy": "start /min \"ntlm-proxy\" cmd /c node_modules\\.bin\\ntlm-proxy",
        "cypress-ntlm": "npm run ntlm-proxy && (cypress-ntlm open & ntlm-proxy-exit)",
      "proxy": "src/launchers/ntlm.proxy.main.js",
      "launch": "src/launchers/cypress.ntlm.js",
      "pnl": "npm run proxy && npm run launch",
      "test": "mocha --require ./test/ts.hooks.js --require source-map-support/register test/**/*.spec.ts",
      "build": "shx rm -rf dist && tsc && shx cp src/commands/index.d.ts dist/commands/ && shx chmod +x dist/launchers/*.js",
      "prepare": "npm run build",
      "coverage": "nyc --require ./test/ts.hooks.js --require source-map-support/register --include \"src\" --extension \".ts\" --exclude \"src/commands/index.d.ts\" --all npm run test",
      "lint": "tslint --project ."
    }

Also I can't do the other thing with Certificates as stated in the link you sent with Corporate CA certificates.

**Comment by bjowes** [comment]
Sometimes getting those environment variables set reliably through package.json is tricky. If you set NODE_TLS_REJECT_UNAUTHORIZED=0 manually in the console and then do `npm run cypress-ntlm', does that work?

If not, please provide debug logs (instructions in the readme)

**Comment by mart834d** [comment]
@bjowes Hey thanks for replying again. Im not entirely sure how to set it through console? - Sorry, Im new, still under enducation to this field. Working on my internship atm :)

Hope u still can help me through it.

**Comment by bjowes** [comment]
Sure. In the console, just type
```
set NODE_TLS_REJECT_UNAUTHORIZED=0
npm run cypress-ntlm
```

**Comment by mart834d** [comment]
@bjowes Thanks it helped!
