### ISSUE TITLE
Help with 504 Gateway Timeout

### ISSUE THREAD

**Issue by hexadeciman** [bjowes/cypress-ntlm-auth#110]
**Issue:** accessing external resources with cypress-ntlm-auth result in 504 Gateway Timeout
example of external ressource: http://js.arcgis.com/3.19/esri/css/esri.css

**Note:** I am under corporate proxy that I can see in my machine's windows settings, defined as: **proxy:** http://rjproxy 
**port:** 8080
**exceptions:** *.company.com;*.companyservices.com
**checked:** don't use the proxy for local (internet) addresses
^ I tried unchecking it.

**What I've already tried:** 

I checked the closed threads reporting the same issue, and attempted to apply the solutions,
using gitbash, I'm running: 

`HTTP_PROXY=http://rjproxy:8080 && HTTPS_PROXY=http://rjproxy:8080 && NO_PROXY=*.company.com,*.companyservices.com && NODE_TLS_REJECT_UNAUTHORIZED=0 && npm run cypress-ntlm`

**configuration:** 
"cypress": "4.1.0",
"cypress-ntlm-auth": "2.2.4"

I see the external ressources are not loaded through the proxy in network tab but through the normal address, is it normal ?
What else could I try ?

**Comment by bjowes** [comment]
Hi @hexadeciman  - you should see all requests in the network tab of developer tools in the browser. Note that in the cypress log you will not see requests to regular static resources (js, html, css). 

If you don't see any external requests there, it could be that there actually is no request occurs (try opening the same site without cypress and compare the network tabs). There might also be a CORS issue. The CORS preflight message is not shown in the network tab, and if it doesn't reach the target server you won't see any request there. But you should see CORS errors in the console.

If you don't see any CORS errors, could you enable debug logging (see the README) and paste it here.

**Comment by hexadeciman** [comment]
unable to reproduce anymore.
