### ISSUE TITLE
504 - Gateway Timeout

### ISSUE THREAD

**Issue by vinothnageswaran** [bjowes/cypress-ntlm-auth#119]
Hi,

I was able to run the plugin without any issues a while ago . However , it now throws 504 - Gateway Timeout error.

The site that I use is, internal site . So I don't need to run the corporate proxy.
If I run the corporate proxy , it takes me to company's proxy pages.
Not much info logged here. Please advise.

 cypress:plugin:ntlm-auth Adding localhost to NO_PROXY to disable localhost proxying +0ms
  cypress:plugin:ntlm-auth Adding 127.0.0.1 to NO_PROXY to disable localhost proxying +3ms
  cypress:plugin:ntlm-auth NTLM auth config API listening on port: 49707 +21ms
  cypress:plugin:ntlm-auth NTLM auth proxy listening on port: 49708 +110ms
  cypress:plugin:ntlm-auth wrote C:\Users\nageva9\AppData\Roaming\cypress-ntlm-auth\cypress-ntlm-auth.port +7ms
  cypress:plugin:ntlm-auth Startup done! +26ms
  cypress:plugin:ntlm-auth {
  cypress:plugin:ntlm-auth   configApiUrl: 'http://127.0.0.1:49707',
  cypress:plugin:ntlm-auth   ntlmProxyUrl: 'http://127.0.0.1:49708'
  cypress:plugin:ntlm-auth } +1ms

**Comment by bjowes** [comment]
Hi @vinothnageswaran - The logs you posted are just from the ntlm-proxy startup. Do no additional logs appear when you start your test? There should be a lot more logging. Otherwise cypress isn't communicating with the ntlm-proxy, check the installation procedure in the docs.

**Comment by vinothnageswaran** [comment]
Hi
This is fixed by it self . I believe there are some proxy issues. Thanks

**Comment by vinothnageswaran** [comment]
Fixed
