### ISSUE TITLE
Not able to open Runs and Log In tabs from Cypress Test Runner using cypress-ntlm-auth

### ISSUE THREAD

**Issue by hari49951** [bjowes/cypress-ntlm-auth#125]
@bjowes Runs and Log In tabs from Cypress Test Runner are not loading using with cypress-ntlm-auth. Was able to open Other tabs. Please see attached images for reference.
![Runs](https://user-images.githubusercontent.com/62620941/89132457-f1ec2c00-d4d9-11ea-93bf-719c3c0ecfae.PNG)
![LogIn](https://user-images.githubusercontent.com/62620941/89132462-f7e20d00-d4d9-11ea-80d2-fa371ea72a9f.PNG)

**Comment by bjowes** [comment]
I tried to reproduce this but saw no issues. However, I don't have a dashboard account. Will create one later and try again to reproduce it.

**Comment by bjowes** [comment]
I just tested this with Cypress 5.0.0. Could not reproduce it, logging in works and I can view the test runs in the Runs tab.
