### ISSUE TITLE
cypress-ntlm-auth stopped working after cypress 4.10.0

### ISSUE THREAD

**Issue by EckiNbg** [bjowes/cypress-ntlm-auth#126]
cypress-ntlm-auth stopped working after capress 4.10.0
Till cypress 4.10.0 the authentication works like a charme, but with newer versions (tried 4.11.0 and 4.12.1) it has stopped working with the message "407: Proxy Authentication Required". Turning back to 4.10.0.

Pls help

**Comment by testtek** [comment]
I am on Cypress@4.12.1 version and cypress-ntlm-auth@2.2.5 works like charm no issues.

**Comment by EckiNbg** [comment]
Thanks, fort he very fast response.
I’ll try again


Von: testtek [mailto:notifications@github.com]
Gesendet: Mittwoch, 12. August 2020 15:54
An: bjowes/cypress-ntlm-auth <cypress-ntlm-auth@noreply.github.com>
Cc: Doennebrink, Eckhardt <e.doennebrink@iq-optimize.de>; Author <author@noreply.github.com>
Betreff: Re: [bjowes/cypress-ntlm-auth] cypress-ntlm-auth stopped working after cypress 4.10.0 (#126)


I am on Cypress@4.12.1<mailto:Cypress@4.12.1> version and cypress-ntlm-auth@2.2.5<mailto:cypress-ntlm-auth@2.2.5> works like charm no issues.

**Comment by bjowes** [comment]
I've just tested the plugin with Cypress 5.0.0 and it seems to work just fine.
I'll close this, if you still have issues @EckiNbg just let me know.

And thanks for helping out @testtek
