### ISSUE TITLE
3.0.0 - cypress-ntlm-auth plugin must be loaded before using this method

### ISSUE THREAD

**Issue by oleghansen** [bjowes/cypress-ntlm-auth#137]
Hi, 
I set up a project recently where I'll be using cucumber and cypress-ntlm-auth. I'm getting this error when running a simple test:
![1](https://user-images.githubusercontent.com/3908524/95871430-f51f5600-0d6d-11eb-8337-62c926aaaa7e.PNG)

As I understood from the update to 3.0.0 I'm not supposed to need anything special in `support/index.js`. I imagined I could solve the problem by using the command `npx cypress-ntlm open`. I do use .feature files and when I try to use the command `npx cypress-ntlm open` or `npx ntlm-proxy` the .feature files are not picked up, only the spec-files in integration/example. Trying the (outdated, as I've understood) approach, adding ntmlAuth in `plugins/index.js` doesn't seem to be valid anymore. 

I'd like to be able to run with authentication either by 1) simply by running yarn cypress open or 2) with npx cypress-ntlm open, but then I'd need the .feature files to be picked up. These are my files:

support/index.js:
```
import './commands';
import 'cypress-ntlm-auth/dist/commands';
```

plugins/index.js (after removing ntlm-related-stuff):
```
const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on) => {
  on('file:preprocessor', cucumber());
}
```

cypress.json
```
{
    "testFiles": "**/*.{feature,features}"
}
```

**Comment by bjowes** [comment]
Hi @oleghansen 

For the plugin to work, you must use `npx cypress-ntlm open` (or `npx cypress-ntlm run`). If you just start cypress, the environment is not setup and you will get the error posted.

In my own test setup, cucumber works fine with the plugin. Your setup looks correct, the only difference is that I have not set the "testFiles" property in cypress.json. I do see both `.spec.js` files and `.feature` files in cypress, and I guess the intent of that property is to only show feature files. Try running with cypress-ntlm with the "testFiles" property removed. If the `.feature` files works in that scenario, please troubleshoot the "testFiles" setting.

I noted that the setting recommended by the cucumber preprocessor docs is `"testFiles": "**/*.feature"`

**Comment by oleghansen** [comment]
Thanks for your reply. Unfortunately this didn't work as expected. Another strange thing that happened is that another set of cypress-files/folders are created when I run `npx cypress-ntlm-open` :
![image](https://user-images.githubusercontent.com/3908524/95948024-0f9a1380-0df0-11eb-9d41-505daf28772b.png)

**Comment by bjowes** [comment]
Please run the npx cypress-ntlm open command from the project root folder
(the e2e folder in your case).

**Comment by oleghansen** [comment]
Thank you for your quick replies. Adding `"testFiles": "**/*.feature"` did the trick. I had that originally but must have tried to switch it out to `"testFiles": "**/*.{feature,features}"` when it didn't pick up feature  files as  expected, but that was probably just me running from cypress folder and not the root folder. Thanks!
