### ISSUE TITLE
npm audit failure since 3.1.2 on package "14"

### ISSUE THREAD

**Issue by Arjan321** [bjowes/cypress-ntlm-auth#151]
Hi, in version 3.1.2 a dependency on package "14" was introduced that causes an (very old) npm audit failure:
```
 Low             Regular Expression Denial of Service
Package         clean-css
Patched in      >=4.1.11
Dependency of   cypress-ntlm-auth [dev]
Path            cypress-ntlm-auth > 14 > gulp-minify-css > clean-css
More info       https://npmjs.com/advisories/785
```

Given that both `14` and `gulp-minify-css` seem unmaintained, can this be fixed somehow in `cypress-ntlm-auth`?

**Comment by bjowes** [comment]
Thanks for reporting this. The package 14 must have been added by mistake, it’s not used by the plug-in. I’m preparing a patched release where I clean up unused dependencies.
