### ISSUE TITLE
problem rin in Docker

### ISSUE THREAD

**Issue by RuslanAisin** [bjowes/cypress-ntlm-auth#171]
Hello!
I have read readme.md and prepare Dockerfile. There is inserted ```RUN npm install -g cypress-ntlm-auth```
In docker-compose.yml insert ```command: cypress-ntlm```
in support/index.js insert ```import "/usr/local/lib/node_modules/cypress-ntlm-auth/dist/commands";```

use command  Docker-compose -f docker-compose.yml up and build ok but test failed with "Error: The cypress-ntlm-auth plugin must be loaded before using this method"
How to fix it?

**Comment by bjowes** [comment]
It sounds like your method should work. To make setup of docker containers easier I created a small sample project. It uses the first method (cypress-ntlm-auth installed both locally and globally) since that is the most portable method. Please see https://github.com/bjowes/cypress-ntlm-auth-docker

**Comment by RuslanAisin** [comment]
> It sounds like your method should work. To make setup of docker containers easier I created a small sample project. It uses the first method (cypress-ntlm-auth installed both locally and globally) since that is the most portable method. Please see https://github.com/bjowes/cypress-ntlm-auth-docker

Thank you it is really help me!
