### ISSUE TITLE
Is there a way to hard set what you want the proxy port to be?

### ISSUE THREAD

**Issue by cdaniel-swi** [bjowes/cypress-ntlm-auth#178]
I'm going to be running this in a pipeline and don't want to always check for the proxy port change. Is there a way to hard set the proxy port?

**Comment by bjowes** [comment]
No there isn’t, but you shouldn’t need to. When starting up cypress-ntlm, it will fetch the proxy url through the config api, so it should work automatically. Why do you want to set it manually?

**Comment by cdaniel-swi** [comment]
I am trying to set it up in my automated CI/CD pipeline. Because I have to use SSO as well as start the proxy. I have to run the npx ntlm-proxy command which generates the api proxy and specifies the port. I then need to set that port on the run command for cypress-ntlm open with the API port. Which means I need to pass the port number from the proxy to the next npm command. I could use a powershell script but it seems over the top instead of just being able to hard set the port from the beginning. If that makes sense.

**Comment by cdaniel-swi** [comment]
Nevermind, This isn't even an issue. I figured a better way
