### ISSUE TITLE
Unable to authenticate running cypress ntlm

### ISSUE THREAD

**Issue by 600rob** [bjowes/cypress-ntlm-auth#218]
Hi 
Im trying to get this plug into work with cypress version 10 on an angular application, windows auth.
Ive installed the plugin successfully but when I run my test, it fails on

  const validationResult = ConfigValidator.validate(ntlmConfig);
    if (!validationResult.ok) {
        throw new Error(validationResult.message);
    }

Resulting in the following error from the cypress test runner:

'Username contains invalid characters or is too long'

Im attempting to navigate to the url using the following approach

cy.ntlm(['localhost:1234'], 'ABC\\firstname.lastmane', 'password')
    cy.visit('https://localhost:1234')

note my username contains a single \ in the string.

i.e ‘ABC\firstname.lasname’

Ive double checked that my username is correct by entering the user credentials manually in the windows authentication pop up
and that works okay.

Tried running the tests without ntlm and i get slightly different result in that the app does not load properly. (probably due to not authenticating) but i think 

Do you have any suggestions on what the issue may be?
p.s. apologies for raising this as an issue as i imagine this is probably more of a config/setup thing on my side but ive not been able to find an answer online.

**Comment by bjowes** [comment]
Hi,
The form ABC\username is actually a combination of domain name and user
name. The domain name is often not required, but you can specify it as a
fourth argument to cy.ntlm. Don't include it in the username argument. So
your example would become:
cy.ntlm(['localhost:1234'], 'firstname.lastmane', 'password', 'ABC')

**Comment by bjowes** [comment]
Closing, please reopen if the problem persists.
