### ISSUE TITLE
Update readme to specify what cypress config file to modify

### ISSUE THREAD

**Issue by dnordahl1** [bjowes/cypress-ntlm-auth#220]
It doesn't appear that `cypress/support/index.js` is created anymore when cypress is installed.  Instead there are several other configuration files in the cypress folder: commands.ts, component.ts, and e2e.ts.  So can the Readme documentation be updated to clarify where to add the ntlm import and initializing commands for the current cypress version?

**Comment by bjowes** [comment]
Thanks for reporting, I'll update the docs.
