### ISSUE TITLE
cypress-ntlm-auth with sorry-cypress - cypress-ntlm-auth plugin must be loaded before using this method

### ISSUE THREAD

**Issue by Lacofab** [bjowes/cypress-ntlm-auth#230]
Hi, 

cypress-ntlm-auth works great locally, but do you have a solution to run cypress-ntlm-auth on sorry-cypress server  ?

sorry-cypress is installed with docker-compose from https://github.com/sorry-cypress/sorry-cypress/blob/master/docker-compose.minio.yml

The error message on sorry-cypress : 
Error: The cypress-ntlm-auth plugin must be loaded before using this method
Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Login and buy stuff`
    at Context.ntlm (webpack:///./node_modules/cypress-ntlm-auth/dist/commands/index.js:35:0)

Thanks

**Comment by bjowes** [comment]
Hi @Lacofab, 
haven't tried using sorry-cypress (but I like the name). When running Cypress through Docker, it is common that Cypress is installed globally which requires special consideration for plugins. See this section in the docs: https://github.com/bjowes/cypress-ntlm-auth#docker-and-global-installs

Let me know if that resolves your issue.

**Comment by bjowes** [comment]
Closed due to lack of feedback
