### ISSUE TITLE
getting "401 unauthorized" behind a corporate proxy

### ISSUE THREAD

**Issue by Anonymous6666666666** [bjowes/cypress-ntlm-auth#236]
Hi, i'm getting the same error "401 Unauthorized" trying to reach my company's website which requires windows authentication. Point is that the same cypress project runs on my colleague's PC with same configurations and accesses. Could you please look up debug logs.
[logs.txt](https://github.com/bjowes/cypress-ntlm-auth/files/11543743/logs.txt)

_Originally posted by @Anonymous6666666666 in https://github.com/bjowes/cypress-ntlm-auth/issues/231#issuecomment-1559199290_

**Comment by Anonymous6666666666** [comment]
#231 I forgot to mention that i can reach company's website in browser which is not being automated by cypress, but cannot open it in when i run browser by cypress. All proxy settings are same as my collegue's. It doesn't seem he bypasses proxy by any other way.
![image](https://github.com/bjowes/cypress-ntlm-auth/assets/134393396/ba856448-6c20-458d-9566-71be04048e58)

**Comment by bjowes** [comment]
Since there were no authentication errors in the logs, the server that replies with 401 does not seem to have been configured with cy.ntlm. Please look at the network tab of developer tools in your browser to determine which server (hostname) is replying with 401, and check if it is included in the config to cy.ntlm.

**Comment by Anonymous6666666666** [comment]
![image](https://github.com/bjowes/cypress-ntlm-auth/assets/134393396/180c0abb-3a76-4563-a996-d713367514b2)
![image](https://github.com/bjowes/cypress-ntlm-auth/assets/134393396/b4f291ca-4540-4bea-af3a-2d61f1540ebe)

**Comment by Anonymous6666666666** [comment]
[logs2.txt](https://github.com/bjowes/cypress-ntlm-auth/files/11564272/logs2.txt)
This is logs from another PC which gets "401 unauthorized" but still passes authentication and runs autotest till the end. Firewall settings are same as mine.

**Comment by Anonymous6666666666** [comment]
![image](https://github.com/bjowes/cypress-ntlm-auth/assets/134393396/70ca793f-08c1-4516-8a92-723702b0c758)
I've tried to put authentication token in cypress environment and it passed. However, it still crashes on halfway gettin "403 forbidden".
![image](https://github.com/bjowes/cypress-ntlm-auth/assets/134393396/e33c85dd-2a4b-47fb-aa0e-c7483bc91ad2)

**Comment by bjowes** [comment]
I think that you are trying to use this plugin for more that what it is capable of. From the logs I can deduce:
* There is traffic to lots of endpoints
* Only one of the endpoints seem to require NTLM authentication (172.16.143.68:80)
* Most endpoints seem to work without authentication
* One endpoint requires Bearer authentication (172.16.143.69:80), but only in a few instances of lots of requests in the logs

This plugin only support NTLM authentication (and Negotiate when using SSO) - Windows Authentication only. Your application seems to deal with several kinds of authentication protocols. Even though the plugin will forward all traffic that isn't NTLM, it slows things down and makes the logs quite hard to read when you configure the plugin to expect NTLM for lots of sites that doesn't use it. I would slim down the cy.ntlm config to include only '172.16.143.68:80'.

As for the other authentication, those are out of scope for this plugin so I cannot support you there.

**Comment by Anonymous6666666666** [comment]
Ok, I'll keep search for solution. Anyway, thanks for your help.
