### ISSUE TITLE
 400: Bad Request on cy.visit()

### ISSUE THREAD

**Issue by hafizjh** [bjowes/cypress-ntlm-auth#238]
Hi @bjowes,

Thanks for this plugin :)

I would like to know if you are able to help me in this?

I received 400 Bad Request when I run this on server which is behind proxy.
I started working on this locally (which also runs behind VPN and proxy) but I didnt have this issue.
The problem only happened when I run the script on my server side.
I provide you the ntlm logs. Please have a look below.

Just FYI, the site is using http protocol, so I dont think the certificates is needed in here.

![image](https://github.com/bjowes/cypress-ntlm-auth/assets/117243147/08289bfa-2a69-4575-b5bb-441f64c50839)

**Comment by bjowes** [comment]
Closed due to lack of feedback
