### ISSUE TITLE
Cannot find name 'cy' Type Error

### ISSUE THREAD

**Issue by Jordan466** [bjowes/cypress-ntlm-auth#253]
Hello.

I'm running Cypress with typescript, and using your plugin to reach an internal company site that requires ntlm. When I add `import "cypress-ntlm-auth/dist/commands";` to my commands.ts, typescript tells me `cy` is no longer available. Everything appears to run correctly though, and my test can reach my site. So I believe this is a typing error.

**Comment by bjowes** [comment]
Thanks for reporting. I found some improvements that can be made. Needs some more work though, so it's a good thing it is usable also without proper type support.
