### ISSUE TITLE
Not sure what to do with the cypress-ntlm plugin i have cloned

### ISSUE THREAD

**Issue by Harshit2318** [bjowes/cypress-ntlm-auth#27]
I have followed all the step but no success. I am not sure what to do with the plugin i have downloaded.
 Do i have to put the plugin folder somewhere?

!----- Here is the Error -------------------------!
CypressError: cy.visit() failed trying to load:

http://fjkdheh.com

The response we received from your web server was:

  > 401: Unauthorized

This was considered a failure because the status code was not '2xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'Actions'

**Comment by bjowes** [comment]
Hi @Harshit2318 ,
Unless you are planning to make changes to the plugin source, you shouldn't need to clone it. If you do 
`npm install --save-dev cypress-ntlm-auth`
in your project root folder, the plugin will be installed in the node_modules folder where it belongs. Then you need to configure Cypress to use the plugin. Did you follow the steps under "Configuration" in the project readme file?

**Comment by bjowes** [comment]
Hi @Harshit2318 , any update on this?

**Comment by bjowes** [comment]
Closing this due to lack of input. @Harshit2318 you are welcome to comment if you need further support.

**Comment by Harshit2318** [comment]
Hi @bjowes ,
Sorry for late reply. That issue related to cypres ntlm is resolved.
I was missing one step in the configuration.

**Comment by Harshit2318** [comment]
Hi @bjowes ,

I have one query-
I have downloaded latest Cypress version 3.3.0. 
Will NTLM plugin work with the latest Cypress vesrion.

Thanks in Advance

**Comment by bjowes** [comment]
Thanks for the feedback @Harshit2318 

Yes, the plugin works fine with 3.3.0.
I have noticed some disturbances with plugin version 1.0.0 on Windows platform (not related to cypress 3.3.0 version), a fix is in the works. If you experience any issues, stick to 0.9.4 for now.
