### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by smit9234** [bjowes/cypress-ntlm-auth#38]
An api that I am testing against allows me to authenticate to it using NTLM, but I receive a "unable to get local issuer certificate error".

I am not sure if this is an issue with cypress-ntlm or the api server

Here is the stack trace
```
    cypress:plugin:ntlm-auth Request to https://my.internal.site:443/ in registered NTLM Hosts+112ms
    cypress:plugin:ntlm-auth Sending  NTLM message type 1 +1ms
    cypress:plugin:ntlm-auth Error while sending NTLM message type 1: { Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' } +11ms
  cypress:plugin:ntlm-auth Cannot perform NTLM handshake. Let original message pass through +2ms
  cypress:plugin:ntlm-auth PROXY_TO_SERVER_REQUEST_ERROR on /it/approvals/process?processIds=81658: { Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
```

**Comment by bjowes** [comment]
Hi @smit9234 , this looks like the CA used for the sites certificate (or applied by a SSL inspection device such as Bluecoat) is a corporate CA. Those won't be trusted by Node by default. You should get hold of the CA cert, store it on your computer, and set the `NODE_EXTRA_CA_CERTS` environment variable to the full path to that certificate file. 

That was a bit brief, ask for clarification if anything is unclear.

**Comment by smit9234** [comment]
This was on my end, closing issue.
