### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by mmenninghaus** [bjowes/cypress-ntlm-auth#42]
Hi!

when executing 
`
npm install --save-dev cypress-ntlm-auth
`
i only get
```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/bjowes/node-http-mitm-proxy.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 140.82.118.3]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mmenninghaus\AppData\Roaming\npm-cache\_logs\2019-05-29T14_17_18_820Z-debug.log
```
Thankfull for any suggestions on this issue.

**Comment by bjowes** [comment]
The latest versions use my own form of one of the dependencies, which is pulled from github. I’m working on getting it merged and properly released to non but that may take some days. 

Seems your machine or network is blocking access to github.com. Try to get that addressed, or use version 1.0.1 which doesn’t require github. 

npm install —save-dev cypress-ntlm-auth@1.0.1

**Comment by mmenninghaus** [comment]
While i am not able to figure out why or how GitHub.com is blocked (other requests work fine), Version 1.0.1 works! Thank you very much!

**Comment by tmoodley** [comment]
Hello, how soon will you fix the github.com issue?

**Comment by bjowes** [comment]
In the latest release 1.0.7 I have replaced the github package with a scoped npm package, so installation should be easier.
