### ISSUE TITLE
seems to be outdated, shouldn't you change it to joeferner?

### ISSUE THREAD

**Issue by kuba13666** [bjowes/cypress-ntlm-auth#43]
https://github.com/bjowes/cypress-ntlm-auth/blob/9356cf66ba5992148c358a015ca9b73783727a17/package.json#L48

**Comment by bjowes** [comment]
I am working with some improvements to get merged into the  joeferner repo, and hopefully to get those released in a proper npm release. Therefore I am waiting a bit before switching over.

**Comment by kuba13666** [comment]
Ok. Can you provide aproximate timeline? Because now I think it is impossible to instal your package?
Thanks for an answer

**Comment by bjowes** [comment]
If you are unable to install, please see #42. 

I’ll probably continue work on this next week, but I can’t say when the updated package from joeferner will be released on npm. Until that happens you still need to install dependencies from github (which should work fine, again see #42)

**Comment by bjowes** [comment]
In the latest release 1.0.7 I have replaced the github package with a scoped npm package, so installation should be easier.
