### ISSUE TITLE
ntlm-proxy randomly crashes

### ISSUE THREAD

**Issue by CarstenKoenig** [bjowes/cypress-ntlm-auth#45]
some of our test-suites randomly crashes the ntlm-proxy process with this error:

```
TypeError: Cannot read property 'ntlm' of undefined
    at setAuthenticationState ({...}\node_modules\cypress-ntlm-auth\src\proxy\server.js:320:26)
    at ClientRequest.proto.request ({...}\node_modules\cypress-ntlm-auth\src\proxy\server.js:400:7)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
```

looking into the `server.js` file there the issues seems to be that `_agents[clientAddress]` seems to be undefined (so the client-address was probably not registered before)

changing this function to

```js
function isAuthenticated(clientSocket, targetHost, isSSL) {
  getAgentFromClientSocket(clientSocket, isSSL, targetHost)
  let clientAddress = getClientAddress(clientSocket);
  let ntlm = _agents[clientAddress].ntlm;
  let auth = (targetHost in ntlm &&
    ntlm[targetHost] === NtlmStateEnum.Authenticated);
  return auth;
}
```

(just adding `getAgentFromClientSocket` to initialize the agent anyway) and updating any usages in this file to include the `isSSL` from the `ctx` object seems to fix the issue for us though

btw: System is running Windows 10 - no clue if this matters

**Comment by CarstenKoenig** [comment]
btw: I tried using the `agent` object returned by `getAgentFromClientSocket` directly but this crashed for some strange reason too (seems to return undefined from time to time)

**Comment by bjowes** [comment]
Hi @CarstenKoenig , I'll have a look later today. Since you are referring to `server.js`, it seems you are using an older version of the plugin. Did you try the current version to see if that resolves the issue?

**Comment by CarstenKoenig** [comment]
we are using `0.9.4` (the setup is not too old - maybe 2-3 weeks) but you are right - there are newer versions - I'll try that and come back to you

**Comment by bjowes** [comment]
I did some improvements on cleanup of agents and config in release 1.0.0 so that might help. Just a heads up: 1.0.2 and up requires git to be installed on the machine where you install the plugin, since one of the dependencies isn't released to npm yet. If that is an issue, please use 1.0.1.

**Comment by CarstenKoenig** [comment]
Update: using 1.0.1 fixed this issue for us

Right now `ntlmReset` seems to cause an error in `ntlm-proxy` but test work without it (before we had to do this when we wanted to change the logged in user mid-test - now just using ntlm-auth again seems to work fine)

Thanks

**Comment by bjowes** [comment]
I'm glad that it was resolved @CarstenKoenig , but I am curios what error you are experiencing with the ntlmReset command?

**Comment by CarstenKoenig** [comment]
if we have `cy.ntlmReset` right before a call to `cy.ntlm` we get this (in Cypress) during the run:

```
CypressError: cy.request() failed on:

http://127.0.0.1:52556/reset

The response we received from your web server was:

  > 504: Gateway Timeout

This was considered a failure because the status code was not '2xx' or '3xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://127.0.0.1:52556/reset
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 2
}
Body: {}

-----------------------------------------------------------

The response we got was:

Status: 504 - Gateway Timeout
Headers: {
  "date": "Wed, 05 Jun 2019 04:35:50 GMT",
  "connection": "keep-alive",
  "transfer-encoding": "chunked"
}
Body: PROXY_TO_SERVER_REQUEST_ERROR: Error: socket hang up


Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'valide Test-Eingaben als Te...'
```

As I understand it this might be related to the app we are developing (the PROXY_TO_SERVER_REQUEST part right?) so it's probably not an issue on your side.

But this did work before the update so I don't know.

**Comment by bjowes** [comment]
The issue with reset has been resolved in the latest release.
