### ISSUE TITLE
NPM install Hangs

### ISSUE THREAD

**Issue by tmoodley** [bjowes/cypress-ntlm-auth#47]
NPM does not continue after install module.  I get the following error:
[..................] / fetchMetadata: sill resolveWithNewModule cypress-ntlm-auth@1.0.6 checking installable status

**Comment by bjowes** [comment]
Hi @tmoodley , this seems odd. Did you try installing again? I've seen cases where temporary network issues cases problems for npm.

However, the latest release 1.0.7 has replaced a github package with a scoped npm package, which might help also for you issue. Could you try with the latest version?

**Comment by kmassicotte** [comment]
NPM install hang was resolved by release 1.0.7 for me, for what it's worth ☺️

**Comment by bjowes** [comment]
Good to head @kmassicotte ! I'm closing this, please reopen if this is still an issue.
