### ISSUE TITLE
Support NTLMv2

### ISSUE THREAD

**Issue by bjowes** [bjowes/cypress-ntlm-auth#50]
The dependency httpntlm which is used to generate the NTLM messages only supports NTLMv1. To better support hardened Windows servers, the plugin needs to support NTLMv2. It is also preferable as a default due to improved security.

#49 may be caused by this limitation.

**Comment by PatrikNyberg** [comment]
Thank you! @bjowes this was a welcome fix for me as well :D I no longer recieve 401 on my NTLMv2 cy.visit()
