### ISSUE TITLE
Add possibility to exclude subpaths from NTLM hosts

### ISSUE THREAD

**Issue by bjowes** [bjowes/cypress-ntlm-auth#64]
Some servers use different authentication modes for different subpaths. The current implementation of the plugin only supports host level configuration of authentication, which is too wide for servers with different authentication on different subpaths (if those are used within the same test case).

The planned solution is to add an optional configuration parameter to the cy.ntlm command, which should accept an array of strings with subpaths to exclude from the NTLM configuration.

Example:
Configure acme.com for NTLM auth:
```
cy.ntlm('http://acme.com', 'user', 'password', 'domain', undefined, undefined, ['/basic-auth', '/anonymous'])
```
This would then apply NTLM authentication to all calls to http://acme.com, except if the path starts with '/basic-auth' or '/anonymous'. For those path the requests will be untouched by the plugin, so any authentication headers set by cypress will be passed on.

**Comment by bjowes** [comment]
This is no longer required since full handshake is implemented since 1.3.0

**Comment by smit9234** [comment]
@bjowes 
I am trying the example above.  Not sure I understand how this implementation works.
Using the example of above, here is what is happening on our site.

We have https://acme.com (uses ntlm).  within acme.com, we have a search field that uses an elastic search api, which is accessed at https://elasticsearch.acme.com, this api uses basic auth.

How would I configure the cy.ntlm to work in that situation?

**Comment by bjowes** [comment]
If use cy.ntlm for acme.com, the plugin won't touch requests to elasticsearch.acme.com since that is another hostname. In the original issue, I understood that you used the basic auth feature of cypress to communicate with the site that uses basic auth. From what you describe now it seems like elasticsearch.acme.com is accessed indirectly by the webpage from acme.com. Since the plugin doesn't support basic auth, that won't work. 

However, if I read the cypress docs correctly, you should be able to use cypress own [basic auth](https://docs.cypress.io/api/commands/visit.html#Add-basic-auth-headers) towards elasticsearch.acme.com - cypress should cache the credentials so they are used when it is called indirectly.
