### ISSUE TITLE
401 error when cy.visit

### ISSUE THREAD

**Issue by PatrikNyberg** [bjowes/cypress-ntlm-auth#70]
Hi @bjowes, sorry if this should be in closed #49 (first time posting issue) or other. Love that you're trying making life easier for us NTLM users!

Tried both on Chrome 76 and Electron 61
NPM wise currently using:
- "cypress": "^3.4.1",
- "cypress-ntlm-auth": "^1.3.0-beta.4"
but also tried downgrading to latest working (but doesn't work any longer):
- "cypress": "^3.3.0",
- "cypress-ntlm-auth": "^1.1.0"

Cypress gui shows NTLM goes well (or if it just registers it), but 401 on cy.visit:
I've tried the credentials directly through api calls and there they work (also tried negative test with faulty creds)
![image](https://user-images.githubusercontent.com/12247356/63270000-893f7b80-c297-11e9-8ad9-b28e4bc60eed.png)

your debug log shows:
![image](https://user-images.githubusercontent.com/12247356/63270045-a2482c80-c297-11e9-9daa-d35f975f6408.png)

our security options is set to, though the NTLMv2 issue i know is fixed as i got it working on your 1.1.0 fix:
![image](https://user-images.githubusercontent.com/12247356/63270069-b2600c00-c297-11e9-9694-f526d2dbc97f.png)

do you have any ideas, i'm running dry on them myself, I've tried following open and closed issues here but really can't get it working

Not sure what more info you need, let me know, and big thanks

**Comment by bjowes** [comment]
Hi @PatrikNyberg 

First a clarification. The NTLM log points in the Cypress GUI are logs of the cy.ntlm calls - setting up NTLM hosts. The actual NTLM handshaking is not logged in Cypress, only in the debug logs of the proxy.

* Did you try with the latest version, 1.3.1?
* Do you have any idea what may have changed on your side since it was working?

**Comment by PatrikNyberg** [comment]
@bjowes thanks for clarification

The only thing that comes to mind is Chrome version update and some npm packages, including cypress-ntlm (I think there was some high security risk warnings after summer so i did according the audit).

not sure if it helps but:
I have now tried roll back to all pre-summer npm versions and it works fine with cypress-ntlm version '^1.2.0'.
If I only update cypress-ntlm from 1.2.0 to newest 1.3.1 (or 1.2.1) and nothing else it stops working with the 401 issue.

**Comment by bjowes** [comment]
> Edit: also tried the other way by updating every other npm package except cypress-ntlm 1.2.0 and it seems to work, any idea if something could've been introduced in 1.2.1 that causes this?

Yes @PatrikNyberg that was a good hint! The only changes between those versions are related to how the workstation name is handled. Are you passing a custom workstation name in your cy.ntlm calls? If so, try removing it, or at least make it uppercase.

**Comment by PatrikNyberg** [comment]
@bjowes hmm I've not been using the domain or the workstation inputs, but I tried with them included and it didn't work.

I tried doing a cy.request() instead of a cy.visit() as I find it gives more information when fail:
Shouldn't the request header include Authorization parameters? (
![image](https://user-images.githubusercontent.com/12247356/63414717-b194ba80-c3fc-11e9-8b43-554af1972eb9.png)

Also tried checking Fiddler how ordinary request to that host looks, and it seems that it does have alot of retries (perhaps normal?) before succeeding, do cy.ntlm() or cy.request() have a config for n:th of retries?
![image](https://user-images.githubusercontent.com/12247356/63416295-7a73d880-c3ff-11e9-98d1-b95898220ab3.png)

**Comment by bjowes** [comment]
You won't see the Authorization header in Chrome since it is added by the proxy, after it has left the browser. I think I will need to see the headers to further troubleshoot this. If you set the environment variable `DEBUG_NTLM_HEADERS=1` before starting ntlm-proxy they will be included in the plugin debug logs. 
Note that exposing these headers publicly could potentially be an attack vector (it will reveal the actual hostnames in your test environment). If you are concerned about this, let me know so we can find an alternate way to submit them securely.

**Comment by bjowes** [comment]
Also, could you try passing in `''` (empty string) as workstation?

**Comment by PatrikNyberg** [comment]
nice, some steps forward here i think @bjowes thanks to the DEBUG_NTLM_HEADERS=1

1. the cy.request() now works if given a correct domain (I have always tried enter domain wrong with 'XX\\'  but should been without backslash 'XX' and i've gotten warning and stopped using domain)
2. the cy.request() don't work with ` ' ' ` (empty string) or not included at all
3. however the cy.visit() still don't want to work with either of above tries

just a curiouos thought is that we are using a load balancer, not sure if potentially could be a scenario where loadbalancer does: cy.ntlm(http://env.test.int) is setup to machine01 and then the cy.visit(http://env.test.int) be to machine02

"If you are concerned about this, let me know so we can find an alternate way to submit them securely." - yes I'm not sure myself what of the information is sensitive so I would appreciate help with this for best secure way, thanks for heads up!

**Comment by bjowes** [comment]
If cy.request works, cy.visit should work too, but there are a few gotchas. cy.request is only one request, while the cy.visit often triggers indirect requests (the cy.visit fetches the main HTLM page, which in turn fetches other resources such as javascript, images, API calls...). Please check in chrome what actually fails during cy.visit - could it be another host which isn't configured with cy.ntlm?

Load balancers can potentially be an issue. NTLM authentication is socket based, so if the load balancer changes the endpoint the authentication fails. It should be possible to configure the load balancer to handle this. Please see comment in [this other issue](https://github.com/bjowes/cypress-ntlm-auth/issues/53#issuecomment-517696289)

And yes, the target info block is part of the sensitive data. But, this is also the data I need to fully troubleshoot the issue. If you have dropbox you could put the logfile there and send a sharing link directly to [my email](mailto:bjowes@gmail.com). Then I will notify you when I have downloaded it and you can take it offline.

**Comment by PatrikNyberg** [comment]
I'm growing a stronger conclusion that this is not a bug of cypress.ntlm but on our hardware/software setup.

Yes as you say there is one HTML page that we call and that one calls 4 other, I noticed that one of  those api's server have a different server IIS version...  "server: Microsoft-IIS/8.0" and the rest have "server: Microsoft-IIS/10.0"

not sure if this could be the problem, but it does seem suspicious that all IIS/10.0 goes well and the 8.0 fails the NTLM.

What do you think, is it worth taking the time to convince the right people to upgrade to 10.0?

**Comment by bjowes** [comment]
Interesting. For sure, it is always good practice to keep up with more modern IIS versions. A couple of quick fixes you could try on your side:
* Set workstation to `''` for the host with IIS 8
* Force use of NTLMv1 for the host with IIS 8. There is a parameter to cy.ntlm for this. This won't work if also this host has the GPO to require NTLMv2.

**Comment by PatrikNyberg** [comment]
I am certain there's been a few SBS moments here but it works now! 

The visit() and request() that failed now works. I've been trial and erroring so much I forget what scenarios I've used in my comments above. It was most likely the correct use of domain without backslashes that seems to have done it, must have forgotten to give the main host the domain info when testing above.

I tried following scenarios of cy.ntlm() on all API's before the visit()
1.  cy.ntlm('http://url.test.int',user,key,domain,user,1); fail (as it should)
2.  cy.ntlm('http://url.test.int',user,key,domain,user,2); works
3.  cy.ntlm('http://url.test.int',user,key,domain,''); works
4.  cy.ntlm('http://url.test.int',user,key,domain,user); works
5.  cy.ntlm('http://url.test.int',user,key,domain); works
6.  cy.ntlm('http://url.test.int',user,key,''); fail
7.  cy.ntlm('http://url.test.int',user,key); fail

Am very greatful for all the help and time you've put in! Thank you

**Comment by bjowes** [comment]
I am glad to hear that it worked out in the end! 

For scenario 6 it is expected to fail, but for scenario 7 the plugin should figure out the domain from the targetInfo block from the server. I will perform some testing on my own to validate that - if it works for me I might contact you again to see what might be different in your case.

**Comment by bjowes** [comment]
Hi @PatrikNyberg 

Just released 1.3.2, where scenario 7 should work again. Would be great if you could validate that it works for you.
