### ISSUE TITLE
Automatic use of logged in user credentials

### ISSUE THREAD

**Issue by bjowes** [bjowes/cypress-ntlm-auth#73]
On Windows, some applications (like Chrome) automatically use the logged on users credentials when performing single sign on authentication (NTLM or Kerberos). It would be easier for the users of this plugin, and more secure, if the plugin could do the same thing. That would mean that username and password would not be required anymore. 

- [x] Implement native module to authenticate with logged in user
- [x] Provide pre-built binaries for the native module to simplify use
- [ ] Proper documentation
- [x] Better validation of SSO configuration
- [x] More unit tests
- [x] Proper error messages for non-Windows hosts

("Wildcard support when specifying hosts" will be done in a separate issue)

**Comment by luis-m-gonzalez** [comment]
Thanks for opening this! This would be the preferred behavior on may corporate environments

**Comment by Tarig0** [comment]
not NTLM but this looks to be promising in how to gain access to the current credentials

**Comment by bjowes** [comment]
After initial investigations this actually seems doable! Implementation is in progress. 
Since it will require a native node module for Windows API calls, I will look into making prebuilt binaries to keep usage of the plugin simple. I'll let you know when there is a beta ready for testing.

**Comment by luis-m-gonzalez** [comment]
Awesome! Getting really excited

**Comment by bjowes** [comment]
I'm thrilled to announce the first Beta of this feature! 
If you are really keen to try this out, you can install version 2.0.0-beta.1 from npm.
Use `cy.ntlmSso(['ntlm-host.company.com', 'ntlm-host2.company.com'])` to register target hosts that should be accessed using the credentials of the user running Cypress. No calls to `cy.ntlm()` are required for hosts using SSO.

The biggest catch is that it uses node_gyp to build a native module for Windows, so you need to have a build chain setup to use it. 
I will move to prebuilt binaries before making a stable version, so the build chain won't be required anymore.

**Comment by bjowes** [comment]
Prebuilt binaries are included since 2.0.0-beta.3, should simplify installation for everyone since you don't need a build chain anymore

**Comment by luis-m-gonzalez** [comment]
That's great, thank you. I'll test the coming week.

**Comment by luis-m-gonzalez** [comment]
It works! O_O

**Comment by bjowes** [comment]
@luis-m-gonzalez - since you requested this feature in the first place I would like to hear your thoughts about configuration. I have planned for the following:
* List of FQDNs for SSO (current implementation)
* Allow wildcards in the FQDNs, like *.internal.com. Should make it easy to allow SSO to the whole intranet
* Pick up the list of trusted sites used by Chrome/IE on Windows and allow SSO to those semi-automatically (just one call to ntlmSso with an extra option to allow this). 

Have just started looking into the third option so I'm not sure how feasible it is, especially in the case where the trusted sites are pushed out through GPO. But I think it would make sense to mimic the browser if possible.  

How does those sound? Would you need something different?

**Comment by luis-m-gonzalez** [comment]
Thanks @bjowes :) At the moment, I only need to authenticate the same FQDN used by the base URL, so I'm generating the Sso call dynamically like this: 

    cy.ntlmSso([Cypress.config().baseUrl
        .replace("/ui", "")
        .replace("http://", "")])

This has worked both for 'localhost' and a standard URL

So I probably wouldn't used the wildcards or semi-automatic option. It may be useful for other teams, but it is hard to tell. My preference would be to get a stable release before adding extra features.

**Comment by bjowes** [comment]
Nice idea to just strip the baseUrl! I think for many users this won't be sufficient, there will often be API's that need authentication even if the frontend allow anonymous access.

For sure, stable release first. I am in the process of extending the unit tests and docs now, then we are ready for 2.0.0. Wildcards and trusted sites will come later.

**Comment by smit9234** [comment]
Will the SSO feature be able to handle other authentication mechanisms, such as Negotiate, Basic, or is just still passing credentials via NTLM?

I am able to to access my main site, but I get 401 unauthorized when accessing API calls that don't use NTLM.

**Comment by bjowes** [comment]
@smit9234 - currently only NTLM is supported. I will look into making Negotiate work too for improved compatibility and security, but that is still a bit into the future since the Negotiate handshake requires some additional steps compared to NTLM. 

For Basic authentication, I am pretty sure Windows doesn’t support SSO for it (from login credentials). Basic authentication may appear in many different contexts, while NTLM and Negotiate are Windows Authentication only. 
A web browser can appear to provide SSO for a site with basic authentication, but this only means you have at some point entered your credentials and they are stored or cached by the browser. 

You can inspect the headers of the 401 you are receiving. The www-authenticate header will tell you which authentication types it accepts.

**Comment by bjowes** [comment]
Released 2.0.0-beta.4 which includes unit tests and validation. Pretty close to a stable release now, just need to do some more documentation.

**Comment by luis-m-gonzalez** [comment]
@bjowes FYI my team decided to start using cypress, an a big part of that decision is because we have this feature available. Thank you very much for your support and your hard work!

**Comment by bjowes** [comment]
@luis-m-gonzalez  - that's great to hear, thanks for sharing!
