### ISSUE TITLE
Can I have '\' in ntlm Username?

### ISSUE THREAD

**Issue by Annilla** [bjowes/cypress-ntlm-auth#74]
I use ntlm with following  example code
```
cy.ntlm('domain', 'ab\\cdefg', 'password')
```
System show Error: Username contains invalid characters or is too long.
Can I have '\\' in ntlm Username?

**Comment by bjowes** [comment]
No, backslash is not a legal character in windows usernames. 

When you see a username containing a backslash, it is actually [domain]\[username]. So pass the domain part as the domain argument and the username part as the username argument.

**Comment by Annilla** [comment]
@bjowes  I got it, thanks a lot!  :+1:
