### ISSUE TITLE
Support for a node module interface?

### ISSUE THREAD

**Issue by ewolfe** [bjowes/cypress-ntlm-auth#75]
I run cypress via `cypress.run` https://docs.cypress.io/guides/guides/module-api.html#cypress-run

What would be the best way to integrate `cypress-ntlm-auth` into a setup that needs a node module interface?

**Comment by bjowes** [comment]
Thanks for the idea @ewolfe - this is now released!

**Comment by ewolfe** [comment]
Amazing, thank you!
