### ISSUE TITLE
The plugin doesn't work with Cypress version 3.5.0

### ISSUE THREAD

**Issue by luis-m-gonzalez** [bjowes/cypress-ntlm-auth#81]
Note: It still works well on Cypress 3.4.1

From the Test Runner:

NTLMSSO {ntlmhosts: [localhost]}

CypressError: cy.visit() failed trying to load:

http://localhost/ui/

The response we received from your web server was:

  > 401: Unauthorized

This was considered a failure because the status code was not '2xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

**Comment by bjowes** [comment]
Thanks for reporting - I can reproduce it. Under investigation.

**Comment by bjowes** [comment]
Apparently [this issue in Cypress](https://github.com/cypress-io/cypress/issues/4780) was released with 3.5.0, which changed the behaviour of the proxy settings of Cypress. It is fairly easy to overcome though, I will make a new release shortly.

For those that cannot wait, you can resolve this by editing the file 
`cypress-ntlm-auth/dist/launchers/cypress-ntlm.js`in your node_modules folder. 
Change this line:
`process.env.NO_PROXY = '';`
to
`process.env.NO_PROXY = '<-loopback>';`

**Comment by bjowes** [comment]
By the way, this only affects sites on localhost - all external hosts should work fine out of the box with 3.5.0
