### ISSUE TITLE
Does not work for site with only Negotiate

### ISSUE THREAD

**Issue by anujmahi** [bjowes/cypress-ntlm-auth#91]
I am getting  Got unexpected error or PROXY_TO_SERVER_SOCKET. Target:download.cypress.io:443 {Error: connect ETIMEDOUT

Can somebody please help why I am getting this issue.

Thanks

**Comment by bjowes** [comment]
Hi @anujmahi - the error you mention is only related to cypress checking with its server if there is a more recent version available. Cypress will work fine regardless if you can reach that server of not. 
* Does the rest of your test work?
* Which version of the plugin are you using?
* Which version of Cypress?

The error could occur if there is some issue with the availability of download.cypress.io, or if you have a firewall blocking the traffic.

**Comment by anujmahi** [comment]
Hi @bjowes 

Thanks for quick response.

- None of my test works as I keep on getting this error.
- I am using Cypress 3.5.0 
_ cypress-ntlm-auth : 2.03
 
I am currently using this inside my office which has firewall.

**Comment by bjowes** [comment]
Since it is Cypress itself that is requesting download.cypress.io, can you start Cypress without the plugin and execute tests? (See the notes in the README, you need to disable the plugin to run Cypress without it)
If not, this is an issue with Cypress and not the plugin. I haven't tested 3.5.0 specifically but earlier versions worked fine without connecting to download.cypress.io.

**Comment by anujmahi** [comment]
The issue got resolved. I just added HTTP_PROXY before starting ntlm-proxy.

But now I am getting 401 for every call. 

I have even downloaded the latest versio @2.0.4

Can you please help . How to get this work ?

**Comment by bjowes** [comment]
I need more info to sort this out. 
* What is your target site?
* Are you using cy.ntlm or cy.ntlmSso to setup your NTLM hosts? How are you calling them? (just need to see the host, not user/password)
* What do the debug logs (from ntlm-proxy) say? Does it perform a NTLM handshake?

**Comment by bjowes** [comment]
Any update on this @anujmahi ?

**Comment by anujmahi** [comment]
Hi @bjowes 

I don't see any ntlm handshake made in my logs.

I am using cy.ntlmsso as well I tried with cy.ntlm with my username and password but didn't find.any luck.

The last line I see in my ntlm proxy log is 
Request to http:// some-domain:80 in registered NTLM Hosts(using SSO)

After that I only see

Removed agent for 127.0.0.1:54109 due to socket.close
Removed agent for 127.0.0.1:54112 due to socket.close

I can't paste the complete log

Can you please help.

It seems that ntlmhand shake is not being called at all in my case.

Thanks

**Comment by bjowes** [comment]
It is a good sign that you saw the 'using SSO' in the logs, that means that your target host has been configured for SSO and the plugin detected the request. However, since you don't get any logs after this, that could mean two things: 
* your site is not responding with 401 to start the handshake. If this is the case, I think you should see your site (or the result from the call if it is an API), look at the network tab in chrome devtools.
* the plugin doesn't receive any response from your site  

Since you had to configure HTTP_PROXY before launching cypress, it could be the case that the site you are trying to reach is internal and the proxy you configured won't forward traffic to it. When setting HTTP_PROXY, try also setting NO_PROXY to the hostname you are trying to reach. Wildcards work too, so if all your internal sites are within *.internal.company.com you could set NO_PROXY to that. Also please add localhost to the NO_PROXY as written in the README.

**Comment by anujmahi** [comment]
@bjowes 

Thanks for the quick response.

I have tried above methods by setting up the NO_PROXY=*.my company.com,localhost
It didn't worked.

I am able to see the site returning 401 in the Cypress browser logs on the left side.

**Comment by anujmahi** [comment]
I am not starting cypress-ntlm from package.json

In one cmd instance I am running ntlm-proxy by setting HTTP_PROXY and NO_PROXY
And in another cmd instance I am running  node_modules\\.bin\\cypress-ntlm open

**Comment by anujmahi** [comment]
Am I missing something in the configuration.

I believe I have configured everything bas per documentation.
I don't understand why ntlmhandshake is not being initiated.

Can I put some log inorder to see what is happening ?

**Comment by bjowes** [comment]
As for your question, there is only one log level (apart from logging NTLM headers) - debug log only.

Could it be that your site has disabled NTLM? If you look at the headers of the 401 response you are receiving in Cypress (click on it and open the console), look for the `www-authenticate` header. Is NTLM included there, or only Negotiate?

If NTLM is missing, it needs to be enabled on the server you are trying to access.

I realize that a debug log for this particular case could be helpful to see what has happened.

**Comment by anujmahi** [comment]
It only includes www-authenticate Negotiate.

Is this the reason I am not able to do so.

And if test how can I by pass this as I cannot ask to enable it. I had to go with what I have.

Any suggestions

**Comment by bjowes** [comment]
Well, unfortunately the plugin only supports NTLM - hence the name cypress-ntlm-auth. I have thought about adding Negotiate support, but that is a fairly large project so I am unsure if/when I would be able to do it. 
If you can't request the server admins to add NTLM, you cannot use Cypress (unless there is another plugin somewhere I am unaware of).

**Comment by anujmahi** [comment]
I believe it is because I am not getting NTLM in www-authenticate response headers, it is not able to start the handshake

Any work around would be really appreciated as I cannot ask the server side to enable NTLM authentication.

**Comment by anujmahi** [comment]
Would love to see this as a feature in the current library.

**Comment by anujmahi** [comment]
Hi @bjowes 

Can you add one feature for Kerberos authentication where , as a user I can setup the KDC token required for Kerberos authentication and rest of the handshake will be taken care by the library .

We have libraries that can generate KDC token and I need you help so that instead of NTLM handshake it can use those KDC toke  to do the authentication.

**Comment by bjowes** [comment]
Well, that could be one way to solve it. 
I have put some effort into making the SSO feature Negotiate compatible. When that is in place, Negotiate can work with Cypress if you use SSO (and only need to sign in as the current user). Would that be sufficient for your needs, or would you still require a way to set the tokens manually?

**Comment by anujmahi** [comment]
Hi @bjowes 

Thank you so much for putting an effort on this.

If SSO can take care of doing the negotiate even for current user , that would be great . As of now only for current user will work.
 
Setting up the KDC token manually was an option that I was thinking of inorder to get the solution done if we don't have a way to  negotiate using the library.

But I have one question , even for negotiate we need the have token which will be required by the server to authenticate, how will you generate the token using SSO.

Thanks

**Comment by bjowes** [comment]
Token generation for the current user is built into Windows and can be accessed through Win32 APIs.  This is the method used by web browsers to perform single sign on. For the NTLM SSO I am already using this method. 

If you are interested in the details, I have a separate library which handles SSO (since it must be built as a native Node.JS addon for Windows) called [node-win-sso](https://github.com/bjowes/node-win-sso)

**Comment by anujmahi** [comment]
If this works and we are able to use the negotiate, it will be enough for us.

This will be really helpful if you can add on those changes and push the code for new release so that I can test the library at my side.

Thanks

**Comment by bjowes** [comment]
Hi @anujmahi - I am pleased to report that a beta version with Negotiate support for SSO is now released (2.1.0-beta.1)! I have just performed a few manual tests, and the unit test suite has not been updated yet so use at your own risk. 

I will continue the work on the unit tests before making a stable release.

**Comment by bjowes** [comment]
Hi @anujmahi - did you try out the beta? If not, the new stable version includes Negotiate support with SSO. Would be great to hear back if it works for you.

**Comment by anujmahi** [comment]
Hi @bjowes 

Sorry for the late reply as I was on vacation. I gave it try to the new version 2.1.0.

It is able to initiate negotiate handshake but fails saying that it didn't get the Negotiate option in the response during the handshake.

I did tried running the ntlm-proxy in DEBUG for negotiate headers and it does passes the negotiate token.
I am not able to understand where it is failing or is it failing because it is expecting negotiate in response while starting the handshake.

Please suggest.

Thanks

**Comment by bjowes** [comment]
Hi @anujmahi,

I would need to see the log or for you to provide a more detailed description of the exchange. You can send the log in an email to me if you don't wan't to paste it here. My email is `my github name`@gmail.com.

What I'm interested in is the exchange between client and server - how many times are Negotiate tokens sent from each side before you get the error message? And are the Negotiate tokens Keberos or NTLM tokens (both are possible within Negotiate). NTLM tokens always start with `TlRMT`

Also, please confirm that you can access the site you are trying to access when doing it manually from the browser. With the same user account you are signed in to windows with.

**Comment by anujmahi** [comment]
Hi @bjowes 

Negotiate tokens are only sent once. The tokens are negotiate as it is starting from YHK.

What I am seeing weired is I tried putting some log comments in your negotiate.manager file to print out the response status code  and what I am getting is 500 , I am not able to understand why.

And I do have access to application on my windows machine

Thanks

**Comment by bjowes** [comment]
You should be able to add custom logs if you follow the same pattern I use
to call the log function. I guess you are trying to add variables to the
logs to see their content, start by removing the variable and see if you
can get the log to work. Then try adding it and make sure the syntax is
correct and that the variable won't be null in some case.

When you say that the tokens are sent once, do you mean once from
ntlm_proxy - or once from ntlm_proxy and once from the server?
