### ISSUE TITLE
Plugin do not work with Cucumber plugin

### ISSUE THREAD

**Issue by varunpradhan** [bjowes/cypress-ntlm-auth#96]
Hi @bjowes 

I have cucumber plugin too along with ntlm-auth

I have added **cy.ntlm('<host>', '<user_name>', '<password>')** inside **Given** block and it failed with an error that **The cypress-ntlm-auth plugin must be loaded before using this method**

example :

Given('I go to URL', () => {
    cy.ntlm('<host>', '<user_name>', '<password>')
    cy.visit(Cypress.env('url'))
    cy.wait(3000)
})

**Comment by bjowes** [comment]
Hi @varunpradhan !

We are using ntlm-auth together with cucumber at work so it should work fine. Since the plugin can't detect the proxy I am guessing there is a configuration issue. 

* Did the plugin work before you started to use cucumber?
* Did you add the initialization code for the plugin in `cypress/plugins/index.js` as described in the readme?
* Are you launching cypress with the plugins launcher (cypress-ntlm) as described in the readme?

**Comment by varunpradhan** [comment]
-Yes the plugin was working before I started to use cucumber.
-Yes I had added the initialization code for the plugin in cypress/plugins/index.js as described in the readme

Below is my index.js file
![image](https://user-images.githubusercontent.com/26091432/72935455-61df6400-3d8b-11ea-864a-0732c568f57a.png)

-Yes I am launching cypress with the plugins launcher (cypress-ntlm) as described in the readme

![image](https://user-images.githubusercontent.com/26091432/72935534-8dfae500-3d8b-11ea-81b6-a490dcd825f5.png)

**Comment by bjowes** [comment]
Thanks for pasting the `plugins/index.js` file, i can see the issue. You have the correct initalization for ntlm-auth and for cucumber separately, but you need to combine them. 
The second `module.exports = ...` overwrites the first assignment to modules.exports, which removes the initalization for ntlm-auth. Try combining them like this:

```javascript
module.exports = (on, config) => {
  on('file.preprocessor', cucumber());
  config = ntlmAuth.initNtlmAuth(config);
  return config;
}
```

**Comment by varunpradhan** [comment]
Hi @bjowes 

Now I am facing this issue:

![image](https://user-images.githubusercontent.com/26091432/72936977-47f35080-3d8e-11ea-9cfb-c1300270d39c.png)

**Comment by bjowes** [comment]
Oh, my bad. I just wrote that code example from my head, didn't test it. Replace `file.preprocessor`with `file:preprocessor`like you had it in the first place.

**Comment by varunpradhan** [comment]
Ya I got it. Yes now it's working. Thank you for the help.
